# Numpy array 마음대로 잘라내기

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
iris = np.loadtxt('iris.csv', delimiter=',', skiprows=1, usecols=[0,1,2,3])

In [3]:
y = np.array([0]*50+[1]*50+[2]*50)

### 팬시 색인
- 위치(인덱스)를 알면 뽑아낼 수 있다


In [4]:
a = np.array([9,3,7,5,6])
a

array([9, 3, 7, 5, 6])

In [5]:
a[::2]

array([9, 7, 6])

In [6]:
a[[0,3,4]] # 팬시 색인 - 인덱스를 넣어주기

array([9, 5, 6])

In [7]:
a[[0,2,-1]]

array([9, 7, 6])

In [9]:
a[[2,4]]

array([7, 6])

In [11]:
mat = np.arange(12).reshape(4,3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
mat[[0,3]] # 행 번호에 인덱스

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [13]:
mat[[3,2,1,0]]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [14]:
mat[[0,0,0,0]]

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [15]:
np.random.permutation(mat)

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 3,  4,  5]])

- 열에 대해서도 인덱스로 팬시 색인을 적용할 수 있다.

In [16]:
mat[:, [2,1,0]]

array([[ 2,  1,  0],
       [ 5,  4,  3],
       [ 8,  7,  6],
       [11, 10,  9]])

In [18]:
mat[:, [0,-1]]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [19]:
a = np.array([1,2,3])

In [20]:
a[0]

1

In [21]:
a[[0]] # 행 번호 자리에 리스트가 들어감

array([1])

In [23]:
a[[0,1]]

array([1, 2])

In [22]:
iris[[0,2,4]] # 행번호 0,2,4 를 골라냄

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [26]:
iris[:, [0,2,3]]

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2],
       [5.4, 1.7, 0.4],
       [4.6, 1.4, 0.3],
       [5. , 1.5, 0.2],
       [4.4, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5.4, 1.5, 0.2],
       [4.8, 1.6, 0.2],
       [4.8, 1.4, 0.1],
       [4.3, 1.1, 0.1],
       [5.8, 1.2, 0.2],
       [5.7, 1.5, 0.4],
       [5.4, 1.3, 0.4],
       [5.1, 1.4, 0.3],
       [5.7, 1.7, 0.3],
       [5.1, 1.5, 0.3],
       [5.4, 1.7, 0.2],
       [5.1, 1.5, 0.4],
       [4.6, 1. , 0.2],
       [5.1, 1.7, 0.5],
       [4.8, 1.9, 0.2],
       [5. , 1.6, 0.2],
       [5. , 1.6, 0.4],
       [5.2, 1.5, 0.2],
       [5.2, 1.4, 0.2],
       [4.7, 1.6, 0.2],
       [4.8, 1.6, 0.2],
       [5.4, 1.5, 0.4],
       [5.2, 1.5, 0.1],
       [5.5, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5. , 1.2, 0.2],
       [5.5, 1.3, 0.2],
       [4.9, 1.5, 0.1],
       [4.4, 1.3, 0.2],
       [5.1, 1.5, 0.2],
       [5. , 1.3, 0.3],
       [4.5, 1.3

In [27]:
iris[:, [3,2,1,0]] #iris[:,::-1]

array([[0.2, 1.4, 3.5, 5.1],
       [0.2, 1.4, 3. , 4.9],
       [0.2, 1.3, 3.2, 4.7],
       [0.2, 1.5, 3.1, 4.6],
       [0.2, 1.4, 3.6, 5. ],
       [0.4, 1.7, 3.9, 5.4],
       [0.3, 1.4, 3.4, 4.6],
       [0.2, 1.5, 3.4, 5. ],
       [0.2, 1.4, 2.9, 4.4],
       [0.1, 1.5, 3.1, 4.9],
       [0.2, 1.5, 3.7, 5.4],
       [0.2, 1.6, 3.4, 4.8],
       [0.1, 1.4, 3. , 4.8],
       [0.1, 1.1, 3. , 4.3],
       [0.2, 1.2, 4. , 5.8],
       [0.4, 1.5, 4.4, 5.7],
       [0.4, 1.3, 3.9, 5.4],
       [0.3, 1.4, 3.5, 5.1],
       [0.3, 1.7, 3.8, 5.7],
       [0.3, 1.5, 3.8, 5.1],
       [0.2, 1.7, 3.4, 5.4],
       [0.4, 1.5, 3.7, 5.1],
       [0.2, 1. , 3.6, 4.6],
       [0.5, 1.7, 3.3, 5.1],
       [0.2, 1.9, 3.4, 4.8],
       [0.2, 1.6, 3. , 5. ],
       [0.4, 1.6, 3.4, 5. ],
       [0.2, 1.5, 3.5, 5.2],
       [0.2, 1.4, 3.4, 5.2],
       [0.2, 1.6, 3.2, 4.7],
       [0.2, 1.6, 3.1, 4.8],
       [0.4, 1.5, 3.4, 5.4],
       [0.1, 1.5, 4.1, 5.2],
       [0.2, 1.4, 4.2, 5.5],
       [0.1, 1

In [28]:
# 각 품종별 첫번째 샘플을 팬시색인으로 뽑기
iris[[0,50,100]] 

array([[5.1, 3.5, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.3, 3.3, 6. , 2.5]])

- 아이리스에서 샘플을 10개 뽑아라

In [35]:
# 방법 1
np.random.permutation(iris)[:10]

array([[5.5, 2.6, 4.4, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [6.3, 2.3, 4.4, 1.3],
       [6.9, 3.2, 5.7, 2.3],
       [5.1, 3.3, 1.7, 0.5],
       [5.5, 4.2, 1.4, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.2, 3.6, 6.1, 2.5],
       [6.4, 3.2, 4.5, 1.5],
       [7.1, 3. , 5.9, 2.1]])

In [33]:
# 방법 2
idx = np.random.randint(150, size=10)
idx

array([ 48, 143, 125, 142,  11,  70,  43, 129, 147,  53])

In [34]:
iris[idx]

array([[5.3, 3.7, 1.5, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [7.2, 3.2, 6. , 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [4.8, 3.4, 1.6, 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [5. , 3.5, 1.6, 0.6],
       [7.2, 3. , 5.8, 1.6],
       [6.5, 3. , 5.2, 2. ],
       [5.5, 2.3, 4. , 1.3]])

In [37]:
# index를 뽑으면 분리된 데이터도 쉽게 불러올 수 있다.
y[idx]

array([0, 2, 2, 2, 0, 1, 0, 2, 2, 1])

In [38]:
# 연습문제
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
label = np.array(['친구','가족','친구'])
label

array(['친구', '가족', '친구'], dtype='<U2')

In [40]:
data[[0,2]]

array([[1, 2],
       [5, 6]])

In [41]:
label[[0,2]]

array(['친구', '친구'], dtype='<U2')

- 아래와 같이 행과 열에 모두 목록을 넣으면, 쌍으로 위치를 지정하게 됨

In [42]:
iris[[0,2,3],[0,2,3]]

array([5.1, 1.3, 0.2])

### 연습문제
- 아이리스 데이터에서, 첫번째 속성(sepal length)의 값이 평균값 보다 큰 샘플들을 뽑아내시오.
- 문제1) 파이썬의 일반적인 방법으로 풀어보시오.
- 문제2) 일반적인 방법 이외에, 먼저 해당 인덱스를 먼저 알아낸 다음 팬시 색인을 적용해보시오.

In [65]:
iris_labels = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
iris = np.loadtxt('iris.csv', skiprows=1, delimiter=',',
                  converters={4: lambda s: iris_labels.index(s.decode())})
iris

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [53]:
avg = [0,0,0,0]

for i in iris:
    for j in range(4):
        avg[j] += i[j]
avg = [i/len(iris) for i in avg]
avg

[5.843333333333335, 3.0540000000000007, 3.7586666666666693, 1.1986666666666672]

In [102]:
idx = []
s = iris[:,0].mean()

for i, l in enumerate(iris): # idx를 뽑아내기 위해 일단 행 번호를 알아야함 => enumerate or range()
    if l[0] > s:
        idx.append(i)
        
display(iris[idx], idx,len(idx))

array([[7. , 3.2, 4.7, 1.4, 1. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [6.1, 2.9, 4.7, 1.4, 1. ],
       [6.7, 3.1, 4.4, 1.4, 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [6. , 2.7, 5.1, 1.6, 1. ],
       [6. , 3.4, 4.5, 1.6, 1. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [6.3, 2.3, 4.4, 1.3, 1. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [6.3, 3.3, 6. , 2.5, 2. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6.3, 2.9, 5.6, 1.8, 2. ],
       [6.5, 3

[50,
 51,
 52,
 54,
 56,
 58,
 61,
 62,
 63,
 65,
 68,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 83,
 85,
 86,
 87,
 91,
 97,
 100,
 102,
 103,
 104,
 105,
 107,
 108,
 109,
 110,
 111,
 112,
 115,
 116,
 117,
 118,
 119,
 120,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 143,
 144,
 145,
 146,
 147,
 148,
 149]

70

In [92]:
# 문제1

data =[]

m = iris[:,0].mean()

for l in iris:
    if l[0] > m:
        data.append(l)
data = np.array(data)
display(m, data, data.shape)

5.843333333333334

array([[7. , 3.2, 4.7, 1.4, 1. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [6.1, 2.9, 4.7, 1.4, 1. ],
       [6.7, 3.1, 4.4, 1.4, 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [6. , 2.7, 5.1, 1.6, 1. ],
       [6. , 3.4, 4.5, 1.6, 1. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [6.3, 2.3, 4.4, 1.3, 1. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [6.3, 3.3, 6. , 2.5, 2. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6.3, 2.9, 5.6, 1.8, 2. ],
       [6.5, 3

(70, 5)

In [94]:
# 문제2
idx = []
m = iris[:,0].mean()

for i in range(150):
    if iris[i,0] > m:
        idx.append(i)
display(iris[idx], idx,len(idx))

array([[7. , 3.2, 4.7, 1.4, 1. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [6.1, 2.9, 4.7, 1.4, 1. ],
       [6.7, 3.1, 4.4, 1.4, 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [6. , 2.7, 5.1, 1.6, 1. ],
       [6. , 3.4, 4.5, 1.6, 1. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [6.3, 2.3, 4.4, 1.3, 1. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [6.3, 3.3, 6. , 2.5, 2. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6.3, 2.9, 5.6, 1.8, 2. ],
       [6.5, 3

[50,
 51,
 52,
 54,
 56,
 58,
 61,
 62,
 63,
 65,
 68,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 83,
 85,
 86,
 87,
 91,
 97,
 100,
 102,
 103,
 104,
 105,
 107,
 108,
 109,
 110,
 111,
 112,
 115,
 116,
 117,
 118,
 119,
 120,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 143,
 144,
 145,
 146,
 147,
 148,
 149]

70

In [102]:
idx = []
s = iris[:,0].mean()

for i, l in enumerate(iris): # idx를 뽑아내기 위해 일단 행 번호를 알아야함 => enumerate or range()
    if l[0] > s:
        idx.append(i)
        
display(iris[idx], idx,len(idx))

array([[7. , 3.2, 4.7, 1.4, 1. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [6.1, 2.9, 4.7, 1.4, 1. ],
       [6.7, 3.1, 4.4, 1.4, 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [6. , 2.7, 5.1, 1.6, 1. ],
       [6. , 3.4, 4.5, 1.6, 1. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [6.3, 2.3, 4.4, 1.3, 1. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [6.3, 3.3, 6. , 2.5, 2. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6.3, 2.9, 5.6, 1.8, 2. ],
       [6.5, 3

[50,
 51,
 52,
 54,
 56,
 58,
 61,
 62,
 63,
 65,
 68,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 83,
 85,
 86,
 87,
 91,
 97,
 100,
 102,
 103,
 104,
 105,
 107,
 108,
 109,
 110,
 111,
 112,
 115,
 116,
 117,
 118,
 119,
 120,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 143,
 144,
 145,
 146,
 147,
 148,
 149]

70

In [103]:
l = ['a','b','c']
for i,n in enumerate(l):
    print(i,n)

0 a
1 b
2 c
