In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.loadtxt('winequality-red.csv', delimiter=';', skiprows=1)

In [3]:
iris = np.loadtxt('iris.csv', skiprows=1, delimiter=',', usecols=[0,1,2,3])

In [5]:
np.savetxt('iris2.csv', iris, delimiter='파이썬') # 윈도우에서는 인코딩이 cp949

In [6]:
# 한글이 있는 경우 encoding='utf-8'이나 'cp949'를 적용시킨다
np.savetxt('iris2.csv', iris, delimiter=',', fmt='%.2f', encoding='utf-8')

##### array를 파일로 저장 / 불러오기

- coin.npy

In [7]:
coin=np.random.randint(2, size=[100,10])
coin[coin.sum(axis=1)>=5]

array([[1, 0, 1, 1, 0, 1, 0, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 0],
       [1, 1, 1, 0, 0, 0, 1, 1, 0, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
       [1, 0, 1, 1, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 0, 1, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 1, 1],
       [1, 0, 0, 1, 1, 0, 1, 0, 0, 1],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 1,

In [8]:
np.savetxt('coin.csv',coin,delimiter=',', fmt='%.2f')

In [13]:
np.save('coin.npy', coin)

In [14]:
x=np.load('coin.npy')
x

array([[0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 1, 1, 0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 0],
       [1, 1, 1, 0, 0, 0, 1, 1, 0, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
       [1, 0, 1, 1, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 1, 0, 1],
       [1, 1, 0, 0, 1, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 1, 1],
       [1, 0, 0, 1, 1, 0, 1, 0, 0, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0,

- test.npy

In [15]:
a = np.arange(12).reshape(4,3)
b = np.array([1,2,3,4,5])
np.save('test.npy', [a,b])

In [16]:
a2, b2 = np.load('test.npy')

In [17]:
b2

array([1, 2, 3, 4, 5])