In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a=[1,2,1,2,3,1,2,3,4]
np.unique(a)

array([1, 2, 3, 4])

In [4]:
any([0,0,0,0,0.0001])

True

In [9]:
all([0,0,0,0,0.0001])

False

In [6]:
a = np.array([[0,1],[0,2]])
print(a)
np.any(a, axis=0) # 하나라도 참이면 참

[[0 1]
 [0 2]]


array([False,  True])

In [8]:
a = np.array([[0,1],[0,2]])
print(a)
np.all(a, axis=0) # 모두가 참이면 참

[[0 1]
 [0 2]]


array([False,  True])

In [10]:
a = np.zeros([100,100])
a[32,17]=1
np.any(a)

True

### 행과 열을 추가하기
- np.c_[a,b] => column
- np.r_[a,b] => row

In [19]:
a= np.zeros([5,3]) + [10,20,30]
a

array([[10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.]])

In [18]:
b=np.arange(10).reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
np.c_[a,b]

array([[10., 20., 30.,  0.,  1.],
       [10., 20., 30.,  2.,  3.],
       [10., 20., 30.,  4.,  5.],
       [10., 20., 30.,  6.,  7.],
       [10., 20., 30.,  8.,  9.]])

In [23]:
x = np.zeros([5,3])+[10,20,30]
y = np.arange(6).reshape(2,3)

In [24]:
np.r_[x,y]

array([[10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [25]:
np.c_[a,[1,2,3,4,5]]

array([[10., 20., 30.,  1.],
       [10., 20., 30.,  2.],
       [10., 20., 30.,  3.],
       [10., 20., 30.,  4.],
       [10., 20., 30.,  5.]])

In [33]:
np.r_[a,np.arange(3).reshape(1,3)]

array([[10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [ 0.,  1.,  2.]])

In [32]:
np.r_[a, [[1,2,3]]]

array([[10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [ 1.,  2.,  3.]])

- 1차원 합치기

In [34]:
np.r_[[1,2,3],[4,5,6]]

array([1, 2, 3, 4, 5, 6])

In [35]:
np.c_[[1,2,3],[4,5,6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
# 연습
# a = np.arange(20).reshape(5,4)에서 옆으로 평균을 구한 후 합치시오

In [39]:
a = np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [51]:
np.c_[a, a.mean(axis=1)]

array([[ 0. ,  1. ,  2. ,  3. ,  1.5],
       [ 4. ,  5. ,  6. ,  7. ,  5.5],
       [ 8. ,  9. , 10. , 11. ,  9.5],
       [12. , 13. , 14. , 15. , 13.5],
       [16. , 17. , 18. , 19. , 17.5]])

In [53]:
a.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [14]:
iris_labels = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
iris = np.loadtxt('iris.csv', delimiter=',', skiprows=1, converters = {4: lambda s: iris_labels.index(s.decode())})


In [15]:
iris[:3]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

# reshape( 차원 변경하기 )

In [56]:
a = np.array([1,2,3,4])
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [57]:
b= np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
c=b.reshape(1,1,3,1,1,2,1,1)

In [59]:
c

array([[[[[[[[0]],

            [[1]]]]],




         [[[[[2]],

            [[3]]]]],




         [[[[[4]],

            [[5]]]]]]]])

In [61]:
c.squeeze()

array([[0, 1],
       [2, 3],
       [4, 5]])

In [64]:
snoopy = plt.imread('snoopy.jpg')
snoopy.shape

(720, 1280, 3)

In [65]:
s2 = np.array([snoopy[:,:,0], snoopy[:,:,1],snoopy[:,:,2]])
s2.shape

(3, 720, 1280)

In [66]:
np.moveaxis(snoopy,2,0).shape

(3, 720, 1280)